#ifndef MBRIDGE_CONFIG_H
#define MBRIDGE_CONFIG_H

#define MBRIDGE_VERSION_MAJOR 0
#define MBRIDGE_VERSION_MINOR 1
#define MBRIDGE_VERSION_PATCH 1

#define MBRIDGE_VERSION ((MBRIDGE_VERSION_MAJOR<<16)|(MBRIDGE_VERSION_MINOR<<8)|(MBRIDGE_VERSION_PATCH))

#define MBRIDGE_VERSION_STR_HELPER(major,minor,patch) #major"."#minor"."#patch

#define MBRIDGE_VERSION_STR_MAKE(major,minor,patch) MBRIDGE_VERSION_STR_HELPER(major,minor,patch)

#define MBRIDGE_VERSION_STR MBRIDGE_VERSION_STR_MAKE(MBRIDGE_VERSION_MAJOR,MBRIDGE_VERSION_MINOR,MBRIDGE_VERSION_PATCH)

#endif // MBRIDGE_CONFIG_H
